#pragma once

#include "drivers/stm32xx.h"

const RCC_OscInitTypeDef rcc_osc_conf = {
	.PLL3 =
		{
			.PLLState = RCC_PLL_ON,
			.PLLSource = RCC_PLL3SOURCE_HSE,
			.PLLM = 2,
			.PLLN = 52,
			.PLLP = 3,
			.PLLQ = 51,
			.PLLR = 2,
			.PLLRGE = RCC_PLL3IFRANGE_1,
			.PLLFRACV = 1835,
			.PLLMODE = RCC_PLL_FRACTIONAL,
		},
	.PLL4 =
		{
			.PLLState = RCC_PLL_ON,
			.PLLSource = RCC_PLL4SOURCE_HSE,
			.PLLM = 5,
			.PLLN = 128,
			.PLLP = 1,
			.PLLQ = 25,
			.PLLR = 5,
			.PLLRGE = RCC_PLL4IFRANGE_1,
			.PLLFRACV = 0,
			.PLLMODE = RCC_PLL_INTEGER,
		},
};

const RCC_ClkInitTypeDef rcc_clk_conf = {
	.ClockType = RCC_CLOCKTYPE_HCLK | RCC_CLOCKTYPE_PCLK1 | RCC_CLOCKTYPE_PCLK2 | RCC_CLOCKTYPE_PCLK3 |
				 RCC_CLOCKTYPE_PCLK4 | RCC_CLOCKTYPE_PCLK5 | RCC_CLOCKTYPE_PCLK6,
	.MLAHBInit =
		{
			.MLAHB_Clock = RCC_MLAHBSSOURCE_PLL3,
			.MLAHB_Div = RCC_MLAHB_DIV1,

		},
	.APB4_Div = RCC_APB4_DIV2,
	.APB5_Div = RCC_APB5_DIV4,
	.APB1_Div = RCC_APB1_DIV2,
	.APB2_Div = RCC_APB2_DIV2,
	.APB3_Div = RCC_APB3_DIV2,
	.APB6_Div = RCC_APB6_DIV2,
};

const RCC_PeriphCLKInitTypeDef rcc_periph_clk_conf = {
	.PeriphClockSelection = RCC_PERIPHCLK_I2C12 | RCC_PERIPHCLK_SAI1 | RCC_PERIPHCLK_UART78 | RCC_PERIPHCLK_CKPER |
							RCC_PERIPHCLK_STGEN | RCC_PERIPHCLK_ADC1 | RCC_PERIPHCLK_QSPI | RCC_PERIPHCLK_ADC2,
	.I2c12ClockSelection = RCC_I2C12CLKSOURCE_PCLK1,
	.Uart78ClockSelection = RCC_UART78CLKSOURCE_PCLK1,
	.Sai1ClockSelection = RCC_SAI1CLKSOURCE_PLL4,
	.Adc1ClockSelection = RCC_ADC1CLKSOURCE_PLL4,
	.Adc2ClockSelection = RCC_ADC2CLKSOURCE_PLL4,
	.QspiClockSelection = RCC_QSPICLKSOURCE_ACLK,
	.StgenClockSelection = RCC_STGENCLKSOURCE_HSI,
	.CkperClockSelection = RCC_CKPERCLKSOURCE_HSI,

};
